#!/usr/bin/env bash

# Dependencies:
# evemu
# inotify-tools
# getopt (util-linux)
# at (optional, for --until)

# TODO: Get mouse device automatically
# Workaround for now is to use evemu-record and evemu-describe

# TODO: (maybe) choose a specific area of screen to keep active

# Specify mouse device. Tip: use `evemu-record` and `evemu-describe` to find this.
dev='/dev/input/event7'

# For killing the process later.
TEMPDIR='/tmp/movemouse'
PIDFILE=$TEMPDIR/PID
KEEPALIVEFILE=$TEMPDIR/KEEPALIVE_PID

# Keep sudo ticket alive so evemu-event doesn't re-prompt.
function keepalive() {
  while true; do
    sudo -v
    sleep 60
  done
}

function move() {
  # Don't do anything if mouse is manually being moved (Check every 2sec).
  if (! sudo inotifywait $dev -qq -t 2); then
    sudo evemu-event $dev --type EV_REL --code REL_X --value $1 &&
      sudo evemu-event $dev --type EV_REL --code REL_Y --value $1 --sync
  else
    sleep 30
  fi
}

function print_help() {
  echo "Usage: movemouse [OPTION]"
  echo "Options:"
  echo "  -g              Start moving the mouse."
  echo "  -s              Stop moving the mouse."
  echo "  --until=TIME    Stop at given time (e.g. 14:30, 'now + 30 minutes')."
  echo "                  Requires -g. Uses 'at' for scheduling."
  echo "  -h              Show this help text and exit."
  exit 0
}

function movemouse() {
  while true; do
    move 10 &&
      move -10
  done
}

PARSED=$(getopt -o 'sgh' -l 'until:' -n 'movemouse' -- "$@")
if [ $? -ne 0 ]; then
  print_help
fi
eval set -- "$PARSED"

G=0
S=0
UNTIL=""

while true; do
  case "$1" in
    -g) G=1; shift ;;
    -s) S=1; shift ;;
    --until) UNTIL="$2"; shift 2 ;;
    -h) print_help ;;
    --) shift; break ;;
    *) print_help ;;
  esac
done

if [ "$S" == "1" ]; then
  if [ -f $PIDFILE ]; then
    kill $(cat $PIDFILE) 2>/dev/null
  fi
  if [ -f $KEEPALIVEFILE ]; then
    kill $(cat $KEEPALIVEFILE) 2>/dev/null
  fi
  rm -rf $TEMPDIR
fi

if [ "$G" == "1" ]; then
  if [ -d $TEMPDIR ]; then
    echo "movemouse is already running. Use -s to stop it first."
    exit 1
  fi

  mkdir -p $TEMPDIR

  sudo -v
  if [ $? -ne 0 ]; then
    echo "sudo authentication failed."
    rm -rf $TEMPDIR
    exit 1
  fi

  keepalive &
  echo $! >$KEEPALIVEFILE

  movemouse &
  echo $! >$PIDFILE

  if [ -n "$UNTIL" ]; then
    if ! command -v at &>/dev/null; then
      echo "Warning: 'at' not found. --until will not work."
      echo "Install it (e.g. 'sudo apt install at' or equivalent)."
    else
      echo "kill \$(cat $PIDFILE) \$(cat $KEEPALIVEFILE) 2>/dev/null; rm -rf $TEMPDIR" | at $UNTIL
    fi
  fi
fi
