#!/usr/bin/env bash

# TODO Get mouse device automatically
# Workaround for now is to use evemu-record and evemu-describe

# TODO detach from terminal / run in background

function move() {
  # Don't do anything if mouse is manually being moved (Check every 5sec).
  if (! inotifywait /dev/input/event9 -qq -t 2); then
    evemu-event /dev/input/event9 --type EV_REL --code REL_X --value 10 &&
      evemu-event /dev/input/event9 --type EV_REL --code REL_Y --value 10 --sync
  fi
}

function move_back() {
  if (! inotifywait /dev/input/event9 -qq -t 2); then
    evemu-event /dev/input/event9 --type EV_REL --code REL_X --value -10 &&
      evemu-event /dev/input/event9 --type EV_REL --code REL_Y --value -10 --sync
  fi
}

function movemouse() {
  while true; do
    move
    move_back
  done
}

if [ "$1" == "--start" ]; then
  echo $$ >/tmp/movemousePID
  movemouse
elif [ "$1" == "--stop" ]; then
  kill $(cat /tmp/movemousePID)
fi
